version: "3.8"

networks:
  default:
    external:
      name: nginx-proxy

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn pythontz.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    environment:
      - VIRTUAL_HOST=python.tz, www.python.tz
      - LETSENCRYPT_HOST=python.tz, www.python.tz
      - LETSENCRYPT_EMAIL=comms@python.tz
    ports:
      - 1338:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
